// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Batxuw0KAYey8RsM2k7RhFqt1nbddXA',
    appId: '1:396372820410:web:d9a4671f516db129b59d83',
    messagingSenderId: '396372820410',
    projectId: 'voter-3de6d',
    authDomain: 'voter-3de6d.firebaseapp.com',
    storageBucket: 'voter-3de6d.appspot.com',
    measurementId: 'G-4BPDW235Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2s7zFnh3KQO57mhGXHoIc5-X3KlvKiuA',
    appId: '1:396372820410:android:ead5d41a34051ac5b59d83',
    messagingSenderId: '396372820410',
    projectId: 'voter-3de6d',
    storageBucket: 'voter-3de6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKudhjs-5KU7dmYz2LNxulRxLNPXX-xng',
    appId: '1:396372820410:ios:e35d30f65124a7bcb59d83',
    messagingSenderId: '396372820410',
    projectId: 'voter-3de6d',
    storageBucket: 'voter-3de6d.appspot.com',
    iosBundleId: 'com.example.voter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKudhjs-5KU7dmYz2LNxulRxLNPXX-xng',
    appId: '1:396372820410:ios:696420b9aab77f3eb59d83',
    messagingSenderId: '396372820410',
    projectId: 'voter-3de6d',
    storageBucket: 'voter-3de6d.appspot.com',
    iosBundleId: 'com.example.voter.RunnerTests',
  );
}
